/*
 * APIMATICCalculator.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/01/2016
 */
using System;
using APIMATICCalculator.PCL.Controllers;
using APIMATICCalculator.PCL.Http.Client;

namespace APIMATICCalculator.PCL
{
    public partial class APIMATICCalculatorClient
    {

        /// <summary>
        /// Singleton access to SimpleCalculator controller
        /// </summary>
        public SimpleCalculatorController SimpleCalculator
        {
            get
            {
                return SimpleCalculatorController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to T controller
        /// </summary>
        public TController T
        {
            get
            {
                return TController.Instance;
            }
        }
        /// <summary>
        /// The shared http client to use for all API calls
        /// </summary>
        public IHttpClient SharedHttpClient
        {
            get
            {
                return BaseController.ClientInstance;
            }
            set
            {
                BaseController.ClientInstance = value;
            }        
        }
        
        /// <summary>
        /// Default constructor
        /// </summary>
        public APIMATICCalculatorClient() { }
    }
}